// Table Section Header Height
#define TABLE_SECTION_HEADER_HEIGHT 27.0

// Week agenda row heights

#define TABLE_ROW_EVENT_HEIGHT 17.0
#define TABLE_ROW_DAY_TITLE_HEIGHT 60.0

//week agenda row widths
#define TABLE_ROW_EVENT_WIDTH_IPHONE 222
#define TABLE_ROW_EVENT_WIDTH_IPAD 226

#define TABLE_ROW_REMINDER_WIDTH_IPHONE 271
#define TABLE_ROW_REMINDER_WIDTH_IPAD 275

// month view dots
#define DOT_RADIUS 4
#define DOT_LINE_HEIGHT 5

#define DOT_RADIUS_IPAD 10

#define TODAY_BOX_OUTER_OFFSET 6
#define TODAY_BOX_INNER_OFFSET 8
#define TODAY_BOX_OUTER_MARGIN 1

#define TODAY_BOX_INNER_OFFSET_IPAD 8

#define IPAD_MONTH_VIEW_ROW_HEIGHT_LANDSCAPE 110
#define IPAD_MONTH_VIEW_ROW_HEIGHT_PORTRAIT 70
#define IPHONE_MONTH_VIEW_ROW_HEIGHT_PORTRAIT 40

#define IPAD_MONTH_VIEW_FONT_SIZE_LANDSCAPE 16
#define IPAD_MONTH_VIEW_FONT_SIZE_PORTRAIT 10


// popover
#define POPOVER_ARROW_WIDTH 18
#define POPOVER_ARROW_HEIGHT 9
#define POPOVER_HALF_ARROW_WIDTH 9
#define POPOVER_BLACK_BORDER_WIDTH 17
#define POPOVER_SHADOW_PADDING 2
#define POPOVER_ARROW_HEIGHT_AND_SHADOW (POPOVER_ARROW_HEIGHT + POPOVER_SHADOW_PADDING)

// fonts
#define MONTH_YEAR_TEXT_SPACING 5.0

// keyboard heights
#define IPHONE_KEYBOARD_PORTRAIT_HEIGHT 216.0f
#define IPHONE_KEYBOARD_LANDSCAPE_HEIGHT 160.0f
#define IPAD_KEYBOARD_HEIGHT 500.0f

// landscape week view
#define LEFT_GRID_PADDING_IPHONE 27.0f
#define EVENT_SQUARE_MIN_HEIGHT_IPHONE 12.0f
#define ALL_DAY_EVENT_ROW_HEIGHT 18.0f

#define EVENT_SQUARE_PADDING_IPAD 2.0f